---
title: "Next_word_pred_model"
author: "Joe Rubash"
date: "December 12, 2018"
output: html_document
---


# plan of attack ("make it work", "make it right", "make it fast")
## Stage one - make a simple model using calculated frequencies from n-grams
1. read in data and make a corpus with all sources
2. to start out sample a small portion of this corpus
3. use qunteda package to create unigram (to lower case, strip punc, remove extra 
white space. etc)
4. create a dictionary to assign integer to unique words in unigram
5. build unigram, bigram and trigram document term matrices
6. split ngrams to give previous word(s) and next word (to predict)
7. calc frequencies
8. to colsum of frequencies to
9. create backoff method to start with highest order n-gram then move to lowest
order n-gram if no solution found


## stage two use smoothing to improve prediction and various methods to spee up
8. figure out how to alter frequencies to predict unkowns
9. su

```{r setup - load data}
# clear environment
rm(list = ls())

knitr::opts_chunk$set(echo = TRUE)

# required libraries
library(tidyverse)
library(forcats)
library(readr)
library(readtext)
library(scales)
library(tidytext)
library(stringr)
library(purrr)
library(quanteda)
library(tm)
library(hunspell)
library(pacman)
p_load("cld2")
p_load("cld3")
library(data.table)
library(knitr)

# Download data-----------------------------------------------------------------
# download and unzip data folder
if(!dir.exists("../data/Coursera-SwiftKey/")){
    file.url <- "https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"
    temp <- tempfile()
    download.file(file.url, temp, mode = "wb")
    unzip(temp, exdir = "../data/Coursera-SwiftKey")
    rm(temp)
}

# Sample data------------------------------------------------------------------

# define sample size, read in all english data files, sample, combine, add lines and save to file as csv
sample.size <- 0.05 # delete sample files and rerun code if changing sample size

# check for file with same sample size in title if not make one
if(file.exists(paste("../data/temp.data/sample.text.",
                                 sample.size,
                                 ".csv",
                                 sep = ""))){
    # read in csv file
    sample.text <- fread(file = paste("../data/temp.data/sample.text.",
                                 sample.size,
                                 ".csv",
                                 sep = ""))
} else{
# create function to read in convert, sample then write to file text data
sample_data <- function(file){
    readLines(con = file,
              skipNul = TRUE,
              encoding="UTF-8") %>%
    sample(.,
           size = sample.size * length(.),
           replace = FALSE) #%>% 
        #data.table(text = .)
    }

# read in, sample, and convert to data.table
sample.blogs <- sample_data(file = "../data/Coursera-SwiftKey/final/en_US/en_US.blogs.txt")

sample.news <- sample_data(file = file("../data/Coursera-SwiftKey/final/en_US/en_US.news.txt", "rb"))

sample.twitter <- sample_data(file =  "../data/Coursera-SwiftKey/final/en_US/en_US.twitter.txt")

# combine all text samples
sample.text <- rbind(sample.blogs, sample.news, sample.twitter) 

# remove unneeded objects
#rm(sample.blogs, sample.news, sample.twitter)

# add lines variable
sample.text[, line := 1:length(sample.text$text)]

# write data.table to file  
fwrite(sample.text, file = paste("../data/temp.data/sample.text.",
                                 sample.size,
                                 ".csv",
                                 sep = ""))
} 

text.a <- c("a", "b", "c")
text.b <- c("d", "e", "f")

test <- c(sample.blogs, sample.news, sample.twitter)
corpus.test <- corpus(test)
corpus.test.sentences <- tokens(corpus.test, what = "sentence") 
corpus.test.4gram <- tokens_ngrams(corpus.test.sentences, n = 4)
```

